workflow_dispatch:
  inputs:
    app_name:
      description: "Nama aplikasi"
      required: true

    package_name:
      description: "Package name"
      required: true

    website_url:
      description: "URL website"
      required: true

    version:
      description: "Versi aplikasi"
      required: true
      default: "1.0.0"
