name: Web to APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL Website"
        required: true
        type: string
        default: "https://example.com"

      app_name:
        description: "Nama APK"
        required: true
        type: string
        default: "TamzWeb"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Inputs
        run: |
          echo "================================"
          echo "WEB TO APK TEST"
          echo "================================"
          echo "App Name : ${{ inputs.app_name }}"
          echo "URL      : ${{ inputs.url }}"
          echo "================================"

      - name: Success
        run: echo "Workflow berhasil dijalankan!"
